spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=EST&createDatabaseIfNotExist=true
    username: root
    password: llld1106
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  path: /Users/shiyaoliao/MyBlogLog
  level:
    com.shaw.demo.controller.CategoryController: DEBUG
    root: WARN